### ISSUE TITLE
README values turned into MathJax

### ISSUE THREAD

**Issue by PythonCoderAS** [LilSpazJoekp/docstrfmt#43]
Hey, I was looking at the README and saw that some of the example parameters, like the example below, turned into MathJx syntax.

```markdown
Example: $thing$
```

> Example: $thing$

It would be advised to use another operator that isn't a `$`.

**Comment by LilSpazJoekp** [comment]
What are you referring to? The placeholders for PyCharm?

**Comment by PythonCoderAS** [comment]
> What are you referring to? The placeholders for PyCharm?

Think so. This is a sample block:

```rst
.. note::

    Note that if you are using a virtual environment detected by PyCharm, this is an
    unneeded step. In this case the path to `docstrfmt` is
    `$PyInterpreterDirectory$/docstrfmt`.
```

**Comment by LilSpazJoekp** [comment]
The `$` must be there. That is what is used for placeholders in IDEA IDEs.

**Comment by PythonCoderAS** [comment]
I see. It needs to be escaped somehow, and I think that using literal format strings would be a better idea. Something like:

```rst
.. note::

    Note that if you are using a virtual environment detected by PyCharm, this is an
    unneeded step. In this case the path to `docstrfmt` is
    ``$PyInterpreterDirectory$/docstrfmt``.
```

**Comment by LilSpazJoekp** [comment]
Yes. Also, since this is only for the README the `.. note::` isn't relevant here since that is a sphinx specific admonition.
