### ISSUE TITLE
Exception type in `:raise:`

### ISSUE THREAD

**Issue by isFakeAccount** [LilSpazJoekp/docstrfmt#50]
It would be nice to have the exception type written like this

```
"""[Summary]

:param [ParamName]: [ParamDescription], defaults to [DefaultParamVal]
:type [ParamName]: [ParamType](, optional)
...
:raises [ErrorType]: [ErrorDescription]
...
:return: [ReturnDescription]
:rtype: [ReturnType]
"""
```

Which follows the [Sphinx-RTD-Tutorial](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html?highlight=raises#the-sphinx-docstring-format)

This also makes the Exceptions clickable.

**Comment by LilSpazJoekp** [comment]
Not sure what you mean. `raises` is supported.

**Comment by isFakeAccount** [comment]
@LilSpazJoekp 
 
Hmm. Maybe it is a bug. Because if I write raises like this

```
:raises Exception: This exception is raised.
```

It gets formatted to 

```
:raises: This exception is raised.
```

**Comment by LilSpazJoekp** [comment]
Right, this should be formatting in the type. I'll take a look and see what's going on.
