### ISSUE TITLE
is this library maintained?

### ISSUE THREAD

**Issue by Goldziher** [LilSpazJoekp/docstrfmt#54]
Hi, i want to use this library but there are some issues and it seems its stale.

**Comment by LilSpazJoekp** [comment]
It is however my time is limited to add support for arbitrary directives. So for the moment I've been adding them as people have been requesting them

**Comment by Goldziher** [comment]
> It is however my time is limited to add support for arbitrary directives. So for the moment I've been adding them as people have been requesting them

I see there is another open issue that would resolve this. And it's been stale for a while. 

Would you accept PRs?

**Comment by LilSpazJoekp** [comment]
I would definitely accept PRs

**Comment by nemesifier** [comment]
I recommend closing this issue.
