### ISSUE TITLE
Orphan directive seemingly not recognized

### ISSUE THREAD

**Issue by nemesifier** [LilSpazJoekp/docstrfmt#62]
I have a few documents that are flagged with the [python-sphinx :orphan: directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html#special-metadata-fields).

The library complains with the following error message:

    Empty `:orphan:` field. Please add a field body or omit completely.

Is this done on purpose or is it unintended?

**Comment by LilSpazJoekp** [comment]
Does this field type normally not have text after it?

**Comment by LilSpazJoekp** [comment]
Answered my own question. No it doesn't and the same goes for :nocomments: and :nosearch:. This will be an easy fix.

**Comment by nemesifier** [comment]
Thank you very much for your fast response.
It's just placed at the beginning of the file.

**Comment by nemesifier** [comment]
Is there a list of directives to ignore?

**Comment by LilSpazJoekp** [comment]
Could you elaborate?

**Comment by nemesifier** [comment]
@LilSpazJoekp could you point out which part of the code I could edit to support this?

E.g.: https://github.com/LilSpazJoekp/docstrfmt/blob/master/docstrfmt/rst_extras.py#L134-L145 ?

**Comment by LilSpazJoekp** [comment]
It's a field so it wouldn't need added but instead you'd need to edit the check for no body child on the field if it is a orphan or other kind of field that is used as a marker.

**Comment by LilSpazJoekp** [comment]
Here: https://github.com/LilSpazJoekp/docstrfmt/blob/master/docstrfmt/docstrfmt.py#L456

**Comment by nemesifier** [comment]
Thank you very much @LilSpazJoekp, it worked :+1: :+1:
