### ISSUE TITLE
install_requires is too strict

### ISSUE THREAD

**Issue by takenori-y** [LilSpazJoekp/docstrfmt#78]
The install_requires often causes conflicts with other dependencies and prevents them from being updated such as sphinx (8.x) and docutils (0.21.x).

https://github.com/LilSpazJoekp/docstrfmt/blob/9eb565b8ef5541d069bac525982fce3abac5aede/setup.py#L53-L62

Do you have any concerns about changing `==` to `>=`?

**Comment by LilSpazJoekp** [comment]
No concerns about changing it. However, there is a minimum version required for docutils. If you want you can open a PR and try loosening the requirements for sphinx and docutils.

**Comment by takenori-y** [comment]
Thank you for your reply. I will send you a PR when I have time.
