### ISSUE TITLE
Sphinx 8.0.0 is out and can't be installed if using docstrmt 1.8.0

### ISSUE THREAD

**Issue by nemesifier** [LilSpazJoekp/docstrfmt#81]
Trying to install sphinx 8.0.0:
```
The conflict is caused by:
    The user requested sphinx~=8.0.2
    docstrfmt 1.8.0 depends on sphinx==7.*
```

I recommend relaxing the requirement and allow both 8.0.X and 7.*.
This module shoulnd't be concerned with the particular sphinx version used, that depends on the project implementing this tool, we shouldn't force it on users. As long as sphinx and black are installed and within the compatible version range, it will be fine.

Do you agree @LilSpazJoekp?

**Comment by LilSpazJoekp** [comment]
This project relies on certain types being importable from sphinx. In the past, there were some breaking changes with sphinx that completely broke docstrfmt. We can bump it to allow 8.* and see if it passes CI.

**Comment by LilSpazJoekp** [comment]
It seem that docstrfmt is incompatible with sphinx 8.*. So unfortunately, it can't be bumped to 8.* until the incompability issues is resolved.
