### ISSUE TITLE
Bug: Line length in pyproject.toml seems to be ignored

### ISSUE THREAD

**Issue by zachcran** [LilSpazJoekp/docstrfmt#85]
When I try to define the line length in my `pyproject.toml`, docstrfmt seems to ignore it. I am using v1.8.0 from PyPI. Am I doing something wrong?

To reproduce:
1. Install docstrfmt from PyPI, `pip install docstrfmt`
2. Create a test `pyproject.toml` with
```
[tool.docstrfmt]
line_length = 70
```
3. Create a test file, `test.rst`, with a line that is too long. I used:
```
this line is too long this line is too long this line is too long this line is too long this line is too long this line is too long this line is too long this line is too long
```
4. Run `docstrfmt test.rst --pyproject-config pyproject.toml`
5. The formatted file has a line length of 88, not 70.

**Comment by LilSpazJoekp** [comment]
That's interesting. I'll look into to fixing that. You should be able to specify the line length for black in pyproject.toml and docstrfmt will also fall back to that. It falls back to black's config because it'd look kinda wonky to have your code a different line length than the docstrings.

**Comment by zachcran** [comment]
Thanks! In my original pyproject.toml, I actually do have `line-length = 80` set for black as well so it is nice to know it should fall back on that as well once this is fixed.

**Comment by LilSpazJoekp** [comment]
Oh that's set to 80? Could you remove the docstrfmt block and see if it formats it to 80?

**Comment by zachcran** [comment]
I tried that and it still formats to 88, unfortunately.

**Comment by LilSpazJoekp** [comment]
Okay thanks. I'll get it fixed.

**Comment by zachcran** [comment]
Thanks! I confirmed that this fixed it in my project as well, in case something more complicated was breaking it there.

**Comment by zachcran** [comment]
I can also confirm that this works with the pre-commit hook without any extra args or changes! (except setting `rev: master` until the next version release)
