### ISSUE TITLE
Question: What is the release schedule of the project?

### ISSUE THREAD

**Issue by zachcran** [LilSpazJoekp/docstrfmt#87]
The title pretty much says it all. What is the release schedule or logic for when to release a new version for this project?

**Comment by LilSpazJoekp** [comment]
There isn't a hard release schedule. After #80 is merged, I plan on publishing v1.9.0.

**Comment by LilSpazJoekp** [comment]
v1.9.0 is live on PyPI!

**Comment by zachcran** [comment]
Thank you! By the way, if you're ever interested in automating your versioning, I would suggest using bumpr (https://github.com/haya14busa/action-bumpr) to automate version tagging with simple labels on PRs. In my experience, it is one line in the CI files to implement it. The hard part would be getting your PyPI publishing action to also trigger automatically after the new version is tagged. I don't have experience with that part, but I have seen it done before!
